# Generated by Django 3.2.7 on 2021-09-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('python', '파이썬'), ('web', '웹'), ('django', '장고')], max_length=30),
        ),
    ]
